/* EDIT WORDING HERE. Keep IDs and calculation names unchanged.
   This plain content file loads without any server or external service. */
(window.MU_CHAPTERS ||= []).push({
  id: 3,
  short: "Center & spread",
  ready: true,
  playTitle: "Sleep remix",
  playDescription: "One dot wanders. Which summaries follow?",
  reference: "Mean: add all values and divide by the count. Median: the middle ordered value, or the average of the two middle values. Mode: the most frequent value. Range: maximum minus minimum. Sample variance: s² = Σ(xᵢ − x̄)² / (n − 1). Sample SD: s = √s². Population variance divides by N. Calculations use full precision; displays round at the end.",
  title: "Finding the middle. Feeling the spread.",
  subtitle: "A few sleepy students. A surprisingly big story.",
  classSleep: [7,9,6,8.5,4,6,5.5,6,9.5,6.5,6.5,8.5,8.5,7.5,6.5,5.5,7,10.5,6.5,6,6,6.5,6.5,4.5,7.5,4,5.5,6,8,6.5,8.5,3,4.5,6,4,9,4,8,8,5,5,6.5,4.5,7,8,9,5.5,8,8.5,7,6,8,7,8,8,8,8,6.5,7.5,6,6,9,7,7,7.5,6,5.5,7,8,6.5,5.5,6,7.5,8,7.5,8.5,7,5,7,8,6.5,6.5,6.5,7.5,8,9,6.5,7.5,6,5,8,6,7.5,8,7,8.5,6,8,6,5.5,7.5,6.5,8,6,6.5,6.5,8.5,7.5,7,7.5,3.5,6.5,8.5,8,7,6,4.5,7.5,8.5,8,7,6.5,8.5,5.5,8.5,6,7,5.5,10,7.5,10.5,5.5,7,9,7.5,9.5,7.5,7,10,4,6.5,5,5.5,7,6,7.5,8.5,7.5,8,8.5,3,5.5,6.5,6.5,6.5,8,8,8,5.5,8.5,6,8,5.5,7,6.5,6.5,8,10,4.5,8,4,8,7.5,8,7,8.5,7,6,6,5,7.5,8,10,7.5,7.5,7,9,9.5,5.5,8,6,6,7.5,5,7,8,6.5,9,4,7],
  focusData: [5, 6, 6, 7, 7, 8, 9],
  practice: [
    {id:"c3-01",concept:"mean",prompt:"Four fictional students slept {data} hours. What is their mean?",data:[6,7,7,8],calculation:"mean",unit:"hours",explain:"Add every value and divide by the number of observations: {sum} ÷ {n} = {mean} hours."},
    {id:"c3-02",concept:"median",prompt:"These sleep values are already sorted: {data}. What is the median?",data:[4,6,7,8,15],calculation:"median",unit:"hours",explain:"The median is the middle value in the ordered list: {median} hours. The unusually long night does not pull it upward."},
    {id:"c3-03",concept:"median",prompt:"Sleep hours: {data}. There are an even number of observations. Find the median.",data:[5,6,8,9],calculation:"median",unit:"hours",explain:"Average the two middle values, {middleA} and {middleB}. The median is {median} hours."},
    {id:"c3-04",concept:"spread",prompt:"A fictional sample has scores {data}. What is the range?",data:[2,4,4,6],calculation:"range",unit:"points",explain:"Range is maximum minus minimum: {max} − {min} = {range} points. It uses only the extremes."},
    {id:"c3-05",concept:"variance",prompt:"A sample has scores {data}. What is its sample variance?",data:[2,4,6],calculation:"variance",unit:"points²",explain:"The mean is {mean}. Squared deviations sum to {ss}. Divide by n − 1 = {df}: s² = {variance} points²."},
    {id:"c3-06",concept:"sd",prompt:"For the sample {data}, what is the sample standard deviation?",data:[2,4,6],calculation:"sd",unit:"points",explain:"Sample variance is {variance} points². Its square root is s = {sd} points. SD returns to the original units."},
    {id:"c3-07",concept:"mean",prompt:"One very large value is added to a dataset. Which statement is most dependable?",choices:["The mean is sensitive to its size.","The median must increase more than the mean.","The standard deviation must stay the same."],answer:0,explain:"The mean uses every value, including the extreme one. The median depends on ordered position; it can change too, but is generally more resistant to extremes."},
    {id:"c3-08",concept:"sd",prompt:"Two groups have the same mean. Must they have the same standard deviation?",choices:["No. Their values can be spread out differently.","Yes. The mean determines the spread.","Only if the values are measured in hours."],answer:0,explain:"Center and spread describe different features. Two groups can balance at the same location while one is much more dispersed."},
    {id:"c3-09",concept:"variance",prompt:"Why does this app divide by n − 1 when calculating sample variance?",choices:["To correct bias when estimating population variance from a sample.","Because the smallest observation is removed.","Because one observation has no variation."],answer:0,explain:"Estimating the mean from the same sample uses one degree of freedom. Under independent, identically distributed sampling with finite variance, dividing by n − 1 gives an unbiased estimator of population variance. Sample SD itself is not exactly unbiased."},
    {id:"c3-10",concept:"sd",prompt:"Every student in a sample has exactly the same score. What is the sample SD?",data:[7,7,7,7],calculation:"sd",unit:"points",explain:"Every deviation from the mean is zero, so the sample SD is {sd}. There is no spread in these observations."},
    {id:"c3-11",concept:"mode",prompt:"Fictional coffee counts: {data}. What is the mode?",data:[0,1,1,1,2,3],calculation:"mode",unit:"cups",explain:"The mode is the most frequent value. Here it is {mode} cup. Unlike the mean, a mode can also describe categories."},
    {id:"c3-12",concept:"sd",prompt:"You convert all sleep measurements from hours to minutes. What happens to the SD?",choices:["It is multiplied by the same conversion factor.","It stays the same because the people are unchanged.","It is divided by the number of people."],answer:0,explain:"Multiplying every observation by a positive constant multiplies the SD by that constant. Variance is multiplied by the square of that constant."},
    {id:"c3-13",concept:"mean",prompt:"You add the same bonus to every score. What happens to the mean and SD?",choices:["The mean increases by the bonus; SD is unchanged.","Both increase by the bonus.","Neither changes."],answer:0,explain:"Adding a constant shifts all values together. Their distances from their new mean stay the same, so SD stays the same."},
    {id:"c3-14",concept:"median",prompt:"Phone-use data have a few extremely high values. Which summary best describes a typical ordered position without being pulled toward those extremes?",choices:["The median.","The range.","The variance."],answer:0,explain:"The median describes the middle ordered position and is resistant to extreme magnitudes. Range and variance describe spread, not center."},
    {id:"c3-15",concept:"sd",prompt:"Does a larger sample SD prove that a group has a larger mean?",choices:["No. More spread does not imply a higher center.","Yes. SD and mean always increase together.","Yes, but only in small samples."],answer:0,explain:"SD describes dispersion around a group's own mean. A group can have a low mean and large SD, or a high mean and small SD."}
  ],
  pairs: [
    {id:"p3-01",left:"Mean",right:"Median",prompt:"I am the balance point. Every value contributes to me.",answer:0,explain:"The mean is the balance point of the data. The median splits the ordered observations around the middle."},
    {id:"p3-02",left:"Standard deviation",right:"Variance",prompt:"Sleep was measured in hours. Which measure of spread is also expressed in hours?",answer:0,explain:"SD has the original units. Variance has squared units because it averages squared deviations with the appropriate denominator."},
    {id:"p3-03",left:"Range",right:"Standard deviation",prompt:"I look only at the largest and smallest observations.",answer:0,explain:"Range is maximum minus minimum. SD uses all observations and their distances from the mean."},
    {id:"p3-04",left:"Sample variance",right:"Population variance",prompt:"You have every member of the population you want to describe. Which formula divides the squared deviations by the population size?",answer:1,explain:"Population variance divides by N. To estimate population variance from a sample, this app uses sample variance with n − 1."}
  ]
});

Object.assign(window.MU_CHAPTERS.find(c=>c.id===3), {"rPractice": [{"concept": "Read R", "prompt": "The first and second lines are which summaries?", "choices": ["Mean, then median.", "Median, then mean.", "Variance, then SD."], "answer": 0, "explain": "The code calls mean() first, then median(). Read the function names as well as the numbers.", "rKey": "c3-summary", "id": "c3-r1"}, {"concept": "Read R", "prompt": "Which result is expressed in hours rather than squared hours?", "choices": ["The second result, from sd().", "The first result, from var().", "Neither result."], "answer": 0, "explain": "R’s var() and sd() use n − 1. Variance is in squared units; SD returns to the measurement’s units.", "rKey": "c3-sd", "id": "c3-r2"}]});
