/* Local numerical routines. No requests, packages, or browser R runtime. */
window.MuMath=(()=>{
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length;
const variance=a=>a.reduce((s,x)=>s+(x-mean(a))**2,0)/(a.length-1);
const sd=a=>Math.sqrt(variance(a));
function lgamma(z){const p=[676.5203681218851,-1259.1392167224028,771.3234287776531,-176.6150291621406,12.507343278686905,-0.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-lgamma(1-z);z--;let x=.99999999999980993;for(let i=0;i<p.length;i++)x+=p[i]/(z+i+1);const t=z+7.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}
function betaCF(a,b,x){let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<1e-30)d=1e-30;d=1/d;let h=d;for(let m=1;m<=200;m++){let m2=2*m,aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<1e-30)d=1e-30;c=1+aa/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<3e-14)break}return h}
function ibeta(x,a,b){if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(lgamma(a+b)-lgamma(a)-lgamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaCF(a,b,x)/a:1-bt*betaCF(b,a,1-x)/b}
function tCDF(t,df){if(!Number.isFinite(t))return t>0?1:0;const v=.5*ibeta(df/(df+t*t),df/2,.5);return t>=0?1-v:v}
const tP=(t,df)=>ibeta(df/(df+t*t),df/2,.5);
function invT(p,df){let lo=-100000,hi=100000;for(let i=0;i<100;i++){const mid=(lo+hi)/2;if(tCDF(mid,df)<p)lo=mid;else hi=mid}return(lo+hi)/2}
function normalCDF(z){const sign=z<0?-1:1,x=Math.abs(z)/Math.SQRT2,t=1/(1+.3275911*x),erf=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x);return(1+sign*erf)/2}
function gammaQ(a,x){if(x<=0)return 1;const gl=lgamma(a);if(x<a+1){let sum=1/a,del=sum,ap=a;for(let n=1;n<500;n++){ap++;del*=x/ap;sum+=del;if(Math.abs(del)<Math.abs(sum)*1e-14)break}return 1-sum*Math.exp(-x+a*Math.log(x)-gl)}let b=x+1-a,c=1e30,d=1/b,h=d;for(let i=1;i<500;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-30)d=1e-30;c=b+an/c;if(Math.abs(c)<1e-30)c=1e-30;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<1e-14)break}return Math.exp(-x+a*Math.log(x)-gl)*h}
const fP=(f,d1,d2)=>ibeta(d2/(d2+d1*f),d2/2,d1/2);
function oneT(a,mu=0){const n=a.length,m=mean(a),s=sd(a),se=s/Math.sqrt(n),t=(m-mu)/se,df=n-1,margin=invT(.975,df)*se;return{n,mean:m,sd:s,se,t,df,p:tP(t,df),low:m-margin,high:m+margin,d:(m-mu)/s}}
function welch(a,b){const va=variance(a),vb=variance(b),v1=va/a.length,v2=vb/b.length,difference=mean(a)-mean(b),se=Math.sqrt(v1+v2),df=(v1+v2)**2/(v1*v1/(a.length-1)+v2*v2/(b.length-1)),t=difference/se,margin=invT(.975,df)*se;return{difference,se,df,t,p:tP(t,df),low:difference-margin,high:difference+margin}}
function anova(groups){const a=groups.flat(),grand=mean(a),between=groups.reduce((s,g)=>s+g.length*(mean(g)-grand)**2,0),within=groups.reduce((s,g)=>s+g.reduce((v,x)=>v+(x-mean(g))**2,0),0),df1=groups.length-1,df2=a.length-groups.length,f=(between/df1)/(within/df2);return{grand,between,within,df1,df2,f,p:fP(f,df1,df2),eta:between/(between+within)}}
function regression(x,y){const mx=mean(x),my=mean(y),sxx=x.reduce((s,v)=>s+(v-mx)**2,0),syy=y.reduce((s,v)=>s+(v-my)**2,0),sxy=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0),b=sxy/sxx,a=my-b*mx,r=sxy/Math.sqrt(sxx*syy),df=x.length-2,sse=y.reduce((s,v,i)=>s+(v-a-b*x[i])**2,0),se=Math.sqrt(sse/df/sxx),t=b/se;return{a,b,r,r2:r*r,df,se,t,p:tP(t,df),sse}}
function chiGOF(observed,probabilities){const n=observed.reduce((a,b)=>a+b,0),expected=probabilities.map(p=>n*p),chi=observed.reduce((s,o,i)=>s+(o-expected[i])**2/expected[i],0),df=observed.length-1;return{n,expected,chi,df,p:gammaQ(df/2,chi/2)}}
function question(q){const f=q.formula,v={...f};let answer;switch(f.kind){case'z':answer=(f.x-f.mean)/f.sd;break;case'prob':answer=normalCDF(f.z);break;case'percent':answer=f.count/f.total*100;break;case'se':answer=f.sd/Math.sqrt(f.n);break;case'df':answer=f.n-1;break;case't':v.se=f.sd/Math.sqrt(f.n);answer=(f.mean-f.mu)/v.se;break;case'd':answer=(f.mean-f.mu)/f.sd;break;case'ci':v.se=f.sd/Math.sqrt(f.n);v.margin=invT(.975,f.n-1)*v.se;v.low=f.mean-v.margin;v.high=f.mean+v.margin;answer=f.bound==='low'?v.low:v.high;break;case'expected':answer=f.row*f.col/f.total;break;case'chiPart':answer=(f.observed-f.expected)**2/f.expected;break;case'predict':answer=f.a+f.b*f.x;break;case'r2':answer=f.r**2;break;case'slopeChange':answer=f.b*f.change;break;case'f':answer=f.msBetween/f.msWithin;break;case'product':answer=f.a*f.b;break;default:throw Error('Unknown calculation '+f.kind)}v.answer=answer;const digits=f.kind==='prob'?4:2,format=x=>Number(x.toFixed(digits)).toLocaleString('en-US',{maximumFractionDigits:digits});let prompt=q.prompt,explain=q.explain;for(const [k,value]of Object.entries(v))if(typeof value==='number'){prompt=prompt.replaceAll('{'+k+'}',format(value));explain=explain.replaceAll('{'+k+'}',format(value))}const rounded=Number(answer.toFixed(digits)),candidates=f.kind==='prob'?[1-rounded,.5,rounded/2,.25]:[rounded+1,rounded-1,rounded*2,0,2];const options=[rounded];for(const n of candidates){const a=Number(n.toFixed(digits));if(!options.includes(a))options.push(a);if(options.length===3)break}return{prompt,explain,options:options.map(n=>({text:format(n)+(!q.unit?'':q.unit==='%'?'%':' '+(Math.abs(n)===1&&{points:'point',hours:'hour',cups:'cup'}[q.unit]||q.unit)),right:n===rounded}))}}
return{mean,variance,sd,normalCDF,tCDF,tP,invT,fP,gammaQ,oneT,welch,anova,regression,chiGOF,question};
})();
